# -*- coding: utf-8 -*-
from Nikitta import SiloReaderWriter


DEUTZ           =   "Deutz_turbine"
MITSHUBISHI     =   "Mitsubishi_turbine"


turbine_name   =   MITSHUBISHI 

DEVICES_PATH   =   ["Devices_data", turbine_name,]
DEVICES_DATA   =   'devices_data'
DEVICES_MAP    =   'devices_map'
DEVICES_CHAR   =   'devices_characteristics'
DEVICES_GUI    =   'devices_gui'
DB_HISTORY_DIR =   [turbine_name, 'History']
DB_PRESENT_DIR =   [turbine_name, 'Present', 'Points']


ALL_KINDS_LIST = ['VALVE', 'THROTTLE', 'SERVO', 'RELAY', 'POTENTIOMETER', 'REV_COUNTER', 'FLOWMETER', 
              'THERMOMETER', 'MANOMETER', 'EXHAUST_SENSOR', 'CURRENT_METER', 'VOLTAGE_METER', 'FREQUENCY_METER']
VALVE, THROTTLE, SERVO, RELAY, POTENTIOMETER, REV_COUNTER, FLOWMETER, THERMOMETER, MANOMETER, EXHAUST_SENSOR, CURRENT_METER, VOLTAGE_METER, FREQUENCY_METER = ALL_KINDS_LIST
              

ATTRIBUTES      =   ['ID', 'ENABLED', 'POINT', 'NAME', 'DIRECTION', 'TYPE',	'KIND',	'CHANNELS',	'CHANNELS_DESCRIPTION',	'SETTINGS',	'CHARACTERISTIC']
ID, ENABLED, POINT, NAME, DIRECTION, TYPE, KIND, CHANNELS, CHANNELS_DESCRIPTION, SETTINGS, CHARACTERISTIC   =   ATTRIBUTES


ALL_DEVICES_NAMES_LIST = ["GAS_VALVE", "WASTEGATE", "MAIN_THROTTLE", "AUXILARY_THROTTLE", "STARTER_FAN", 
                      "IGNITION", "OIL_PUMP", "REV_COUNTER_1ST", "REV_COUNTER_2ND", "FLOWMETER_AIR", 
                      "FLOWMETER_GAS", "MANOMETER_INTROL", "MANOMETER_BOTLAND", "THERMOCOUPLE_K", 
                      "LABJACK_TEMP_SENSOR",]
GAS_VALVE, WASTEGATE, MAIN_THROTTLE, AUXILARY_THROTTLE, STARTER_FAN, IGNITION, OIL_PUMP, REV_COUNTER_1ST, REV_COUNTER_2ND, FLOWMETER_AIR, FLOWMETER_GAS, MANOMETER_INTROL, MANOMETER_BOTLAND, THERMOCOUPLE_K, LABJACK_TEMP_SENSOR, = ALL_DEVICES_NAMES_LIST
    
#channels types
DIO, AIN, DAC, TIO, CIO, NOT = ['DIO', 'AIN', 'DAC', 'TIO', 'CIO', 'NOT']
MAX_CHANNEL = {DIO: 22, AIN: 13, DAC: 2, TIO: 7, CIO: 2, NOT: 1}
#devices types
DIGITAL_PULSE, DIGITAL, ANALOG = ['DIGITAL_PULSE', 'DIGITAL', 'ANALOG']

#Settings
MODE, VALUE, VOFFSET, GAIN, SAVE_TIME     =  'mode', 'value', 'voffset', 'gain', 'save_time'
  
#start dirs

client = SiloReaderWriter.SiloReaderWriter()  
sleep_time      = client.sleep_time
avarage_time    = 0.1

